<?php

function book_tours_help($path, $arg) {
    switch ($path) {
        case 'quantri/help':
            return '<p>' . t('Book a Tour') . '</p>';
    }
}

function book_tours_permission() {
    return array(
        'administer book_tours' => array(
            'title' => t('Book a Tour'),
            'description' => t('Book a Tour'),
        ),
    );
}

function book_tours_menu() {
    $items['user/book_tours'] = array(
        'title' => 'Book a Tour',
        'description' => 'Book a Tour',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('book_tours_main'),
        'access arguments' => array('administer book_tours'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'book_tours.inc'
    );

    return $items;
}
