<?php

function manage_tours_permission() {
    return array(
        'administer manage_tours' => array(
            'title' => t('Quản lý tài sản'),
            'description' => t('Quản lý tài sản'),
        ),
    );
}

function manage_tours_menu() {
    $items = array();
    $items['manage/manage_tours'] = array(
        'title' => 'Manage tours',
        'description' => 'Manage tours',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('manage_tours_main'),
        'file' => 'manage_tours.inc',
        'access arguments' => array('administer manage_tours'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['manage/manage_tours/detail/%'] = array(
        'title' => 'Detail a tour',
        'description' => 'Detail a tour',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('manage_tours_detail', 3),
        'file' => 'manage_tours_detail.inc',
        'access arguments' => array('administer manage_tours'),
        'type' => MENU_CALLBACK
    );

    return $items;
}
