<?php

/**
 * Implementation of hook_menu().
 */
function mymodule_menu() {
    return array(
        'node/%node/edit_story/%dialog_js' => array(
            'title' => 'Edit your story',
            'page callback' => 'mymodule_dialog_story_form_handler',
            'page arguments' => array(1, 3), // we pass node object and dialog ajax marker to our new function
            'access callback' => 'node_access', // We allow to edit this field if user has permissions to edit node
            'access arguments' => array('update', 1),
        )
    );
}
/**
* Retrieves the form and makes it work via dialog
*/ 
function mymodule_dialog_story_form_handler($node, $ajax) {
  // if user has js enabled...
  if ($ajax) {
    dialog_display(TRUE);
    
    $content = drupal_get_form('mymodule_dialog_story_form_builder', $node);
    $title = t('Edit your story');
    
    
    
    if (dialog_display()) {        
      $output[] = dialog_command_display($content, array('title' => $title, 'draggable' => false, 'resizable' => false, ));
    } else {      
      $output[] = dialog_command_reload();
    }
       
    
    ajax_deliver(array('#type' => 'ajax', '#commands' => $output));
  
  } else {
    // User has js disabled
    return drupal_get_form('mymodule_dialog_story_form_builder', $node);
  }
  
}

/**
* Builds the form
*/ 
function mymodule_dialog_story_form_builder($form, $form_state, $node) {
  $form = array();
  form_load_include($form_state, 'inc', 'node', 'node.pages');
  $form = node_form($form, $form_state, $node);
  
  // basically, we hide everything except 'body' field
  foreach (element_children($form) as $key) {
    if ($key != 'body') {    
      $form[$key]['#access'] = FALSE;
    }
  }
  
  $form['submit'] = $form['actions']['submit'];
  $form['submit']['#weight'] = 100;
  $form['submit']['#attributes'] = array('class' => array('use-ajax-submit'));
  
  
  $form['#process'][] = 'dialog_process_ajax_form';
  $form['#submit'][] = 'mymodule_dialog_story_form_submit';
  
  return $form;  
}

function mymodule_dialog_story_form_submit($form, &$form_state) {
  // Tell Dialog that we want to close it after form submit
  drupal_static_reset('dialog_display');
  
  // We also don't want to redirect the form needlessly.  The redirected page
  // would have loaded in the dialog.  We'll be dismissing that dialog. If a
  // destination was specified we will handle that with a dialog_command.
  $form_state['no_redirect'] = true;
}